
package com.ibayad.bank.atlantique.registration.api;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BankAccountRegistrationServiceService", targetNamespace = "http://api.registration.atlantique.bank.ibayad.com/", wsdlLocation = "file:/D:/Bank_Atlantique/BankAccountRegistrationService.wsdl")
public class BankAccountRegistrationServiceService
    extends Service
{

    private final static URL BANKACCOUNTREGISTRATIONSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.ibayad.bank.atlantique.registration.api.BankAccountRegistrationServiceService.class.getName());

//    static {
//        URL url = null;
//        try {
//            URL baseUrl;
//            baseUrl = com.ibayad.bank.atlantique.registration.api.BankAccountRegistrationServiceService.class.getResource(".");
//            url = new URL(baseUrl, "file:/D:/Bank_Atlantique/BankAccountRegistrationService.wsdl");
//        } catch (MalformedURLException e) {
//            logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/Bank_Atlantique/BankAccountRegistrationService.wsdl', retrying as a local file");
//            logger.warning(e.getMessage());
//        }
//        BANKACCOUNTREGISTRATIONSERVICESERVICE_WSDL_LOCATION = url;
//    }

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.ibayad.bank.atlantique.registration.api.BankAccountRegistrationServiceService.class.getResource(".");
            url = new URL(baseUrl, "file:/E:/BABF/WSDL/BankAccountRegistrationService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/E:/BABF/WSDL/BankAccountRegistrationService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BANKACCOUNTREGISTRATIONSERVICESERVICE_WSDL_LOCATION = url;
    }
    
    public BankAccountRegistrationServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankAccountRegistrationServiceService() {
        super(BANKACCOUNTREGISTRATIONSERVICESERVICE_WSDL_LOCATION, new QName("http://api.registration.atlantique.bank.ibayad.com/", "BankAccountRegistrationServiceService"));
    }

    /**
     * 
     * @return
     *     returns BankAccountRegistrationService
     */
    @WebEndpoint(name = "BankAccountRegistrationServicePort")
    public BankAccountRegistrationService getBankAccountRegistrationServicePort() {
        return super.getPort(new QName("http://api.registration.atlantique.bank.ibayad.com/", "BankAccountRegistrationServicePort"), BankAccountRegistrationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankAccountRegistrationService
     */
    @WebEndpoint(name = "BankAccountRegistrationServicePort")
    public BankAccountRegistrationService getBankAccountRegistrationServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://api.registration.atlantique.bank.ibayad.com/", "BankAccountRegistrationServicePort"), BankAccountRegistrationService.class, features);
    }

}
